[tool.poetry]
name = "djpy"
version = "0.1.0"
description = "music app"
authors = ["Jansen"]

[tool.poetry.dependencies]
python = "^3.9"
django = "3.2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
